name: weipin
version: 0.0.1+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.5.4
  dio: ^4.0.6
  webview_flutter: ^0.3.10+2
  pin_code_fields: ^7.4.0
  flutter_webview_plugin: ^0.4.0
  package_info_plus: ^3.0.3
  shared_preferences: ^2.0.15
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: weipinIcon   #指定一个字体名
      fonts:
        - asset: assets/font/iconfont.ttf
  assets:
    - assets/images/login/logo.png
    - assets/images/login/logo_screen.png
    - assets/images/login/logo_text.png
    - assets/images/login/tips.png
    - assets/images/cinfo/date.png
    - assets/images/cinfo/name.png
    - assets/images/cinfo/resume.png
    - assets/images/cinfo/sex.png
    - assets/images/cinfo/progress1.png
    - assets/images/cinfo/progress2.png
    - assets/images/cinfo/progress3.png
    - assets/images/cinfo/data_2.png
    - assets/images/cinfo/close.png
    - assets/images/home/me.png
    - assets/images/home/me_hover.png
    - assets/images/home/job.png
    - assets/images/home/job_hover.png
    - assets/images/home/center.png
    - assets/images/home/edit.png
    - assets/images/home/center_01.png
    - assets/images/home/center_02.png
    - assets/images/home/center_03.png
    - assets/images/home/center_04.png